services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: jobsniper_mailer
    restart: unless-stopped
    ports:
      - "1026:1025"
      - "8083:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###
